创建目录 ./runtime/ 成功.
创建目录 ./classes/ 成功.
创建目录 ./commons/ 成功.
创建目录 ./public 成功.
创建目录 ./public/uploads/ 成功.
创建目录 ./public/css/ 成功.
创建目录 ./public/js/ 成功.
创建目录 ./public/images/ 成功.
创建目录 ./admin/ 成功.
创建目录 ./admin/models/ 成功.
创建目录 ./admin/controls/ 成功.
创建目录 ./admin/views/ 成功.
创建目录 ./admin/views/default 成功.
创建目录 ./admin/views/default/public/ 成功.
创建目录 ./admin/views/default/resource/ 成功.
创建目录 ./admin/views/default/resource/css/ 成功.
创建目录 ./admin/views/default/resource/js/ 成功.
创建目录 ./admin/views/default/resource/images/ 成功.
创建文件 ./commons/functions.inc.php 成功.
创建文件 ./admin/controls/common.class.php 成功.
创建文件 ./admin/controls/index.class.php 成功.